project:
  type: website
  resources:
    - fonts/*
  render: [index.qmd, page_*.qmd, "!page_demo.qmd"]

website:
  title: "CNC Austria 2026"
  search: false
  description: "Auswertungen und Analyse für die City Nature Challenge in Österreich."
  repo-url: "https://github.com/HannesOberreiter/city-nature-challenge-austria-2026"
  repo-actions: "edit"

  navbar:
    right:
      - icon: person-lines-fill
        text: ""
        file: page_about.qmd
      - icon: github
        href: "https://github.com/HannesOberreiter/city-nature-challenge-austria-2026"
    left:
      - file: index.qmd
        text: "Übersicht"
      - text: "Regionen"
        menu:
          - file: page_amstetten_waidhofen_ybbs.qmd
            text: "Amstetten - Waidhofen/Ybbs"
          - file: page_elsbeere_wienerwald.qmd
            text: "Elsbeere Wienerwald"
          - file: page_innsbruck.qmd
            text: "Innsbruck"
          - file: page_kaernten.qmd
            text: "Kärnten"
          - file: page_krems_wachau_melk.qmd
            text: "Krems - Wachau - Melk"
          - file: page_naturparke_noe.qmd
            text: "Naturparke NÖ"
          - file: page_neusiedler_see_seewinkel.qmd
            text: "Neusiedler See/Seewinkel"
          - href: page_salzburg.qmd
            text: "Salzburg"
          - file: page_st_poelten.qmd
            text: "St. Pölten"
          - file: page_steiermark.qmd
            text: "Steiermark (Graz)"
          - file: page_steyr.qmd
            text: "Steyr"
          - href: page_vorarlberg.qmd
            text: "Vorarlberg"
          - file: page_wien.qmd
            text: "Wien"
      - text: "Analysen"
        menu:
          - file: page_primeval_forest_relict_beetle.qmd
            text: "Urwaltreliktkäfer"
          - href: https://hannesoberreiter.github.io/inat-austria-city-challenge-2025/
            text: "CNC 2025 🔗"
          - href: https://hannesoberreiter.github.io/inat-austria-city-challenge-2024/
            text: "CNC 2024 🔗"
          - href: https://hannesoberreiter.github.io/inat-austria-city-challenge-2023/
            text: "CNC 2023 🔗"
format:
  html:
    code-fold: true
    embed-resources: false
    include-in-header:
      - file: assets/customMetaTags.html
    link-external-icon: false
    theme:
      light: [flatly, assets/fonts.scss]
      dark: [darkly, assets/fonts.scss]
    css: assets/styles.css
    toc: true
